app:
  name:         Varys     # its unclear what purpose app.name serves since javafx.title seems to take its place
  description:  a sample webcrawling service

spring:
  jmx:
    enabled: false
  jackson:
    serialization:
      indent_output: true

javafx:
  title: ${app.name}
  appicons:
    - ./spider.png

webcrawl:
  enums:  # these provide choices for constained values, or min/max values
    maxDepth:   1000
    maxMinutes: 300
    outputFormats:
      - json
      - xml
      - yaml
    useragents:   # this is an unofficial random sampling of some useragents, since these influence webcrawling results
      - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36                   #chrome on Mac
      - Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0                                                                   #Firefox PC
      - Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.23 (KHTML, like Gecko) Version/10.0 Mobile/14E5239e Safari/602.1   #iphone safari
      - Mozilla/5.0 (Linux; Android 5.1.1; Nexus 5 Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.65 Mobile Safari/537.36 # Android
      - Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.4; en-US; rv:1.9.2.24) Gecko/20111103 LYnX/2.4 #lynx text based browser
  defaults:   # these are the configuration defaults, the UI allows overriding them
    outputFormat: xml
    outputPath: /Desktop  #this path is appended to the user's home directory to create a starting point
    useragent:  ${webcrawl.enums.useragents[0]}
    initialUrl: http://wiprodigital.com
    stayInDomain: true                 # stay in domain (don't go to another domain)
    allowSubdomains: true              # if inside domain are subdomains ok?
    minutesLimit: 1                    # max time
    depthLimit: 10                     # max depth
    linkTypes:                         #specify tag[attribute] combinations that contain urls that crawler should report
      - a[href]
      - link[href]
      - iframe[src]
      - embed[src]
      - input[src]
      - script[src]
      - img[src]
      - object[data]
      - q[cite]
      - del[cite]
